[build]
base = "."
command = "npm install --prefix client && npm run build --prefix client"
publish = "client/dist"

[build.environment]
NODE_VERSION = "20.10.0"
NPM_VERSION = "10.6.0"

[[redirect]]
from = "/"
to = "index.html"
status = 200
